name: VitalSkull
version: @version@
main: com.tamrielnetwork.vitalskull.VitalSkull
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to get their own skull.
commands:
  vitalskull:
    description: "Main command"
    usage: "/vitalskull"
permissions:
  vitalskull.own:
    description: "Permission to get your own head"
    default: op